name: Setup infrastructure and deploy your app to AWS S3

on: [workflow_dispatch]

jobs:
  deploy: 
    uses: gagans-test-org/.github/.github/workflows/create_infrastructure.yml@main
    with:
      application_name: gagan-test
      application_id: 123
      aws_region: us-west-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
